### ISSUE TITLE
训练较大的数据集

### ISSUE THREAD

**Issue by Egbert77** [LBH1024/CAN#11]
您好，请问如果想在该模型上训练类似HMER100K的数据集，需要调整什么超参数吗

**Comment by LBH1024** [comment]
> 您好，请问如果想在该模型上训练类似HMER100K的数据集，需要调整什么超参数吗

你好，在HME100K上可以将weight_decay调小一些，除了backbone之外的dropout可以设置为false，因为在大数据集上不容易过拟合。

**Comment by Egbert77** [comment]
好的，非常感激您的建议
