### ISSUE TITLE
params['word_num'] in yaml

### ISSUE THREAD

**Issue by Lllllolita** [LBH1024/CAN#13]
请问params['word_num']这个参数的具体数值是多少呢？好像没有在config.yaml文件中看到相关设置。

**Comment by Lllllolita** [comment]
请问word_num应该是20吗？查看DWAP的仓库发现该项目似乎设置为了20 @LBH1024

**Comment by LBH1024** [comment]
你好，word_num指的是符号种类数，从数据集的dict可得，在CROHME数据集上word_num是111。

**Comment by Lllllolita** [comment]
好的，非常感谢您的回答
