### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by SuperHHzy** [LBH1024/CAN#14]
请问在32GB RAM 的Tesla V100上需要训练多久？

**Comment by LBH1024** [comment]
你好，训练需要1天左右。

**Comment by SuperHHzy** [comment]
谢谢你的回复。
另外有个问题想要请教
在执行**python train.py --dataset CROHME**的时候 需要指定‘--check’吗？如果需要应该怎么做呢？

**Comment by SuperHHzy** [comment]
> 

当我执行 **python train.py --dataset CROHME**这句命令的时候，给我返回了**KeyError: 'x'**这样一个错误，我不知道是哪里出了问题，请问你明白吗？
