### ISSUE TITLE
Can you provide a pre trained model？

### ISSUE THREAD

**Issue by Note-Liu** [LBH1024/CAN#2]
Can you provide a pre training model？ThX.

**Comment by LBH1024** [comment]
> Can you provide a pre training model？ThX.


Sorry we do not plan to release the pre-trained model for now. 
You can train one using a GPU with 32GB RAM. The whole training process takes around one day.
And in order to get the best result on a certain dataset (e.g., CROHME 2019), you need to set it as the validation dataset.

**Comment by Note-Liu** [comment]
> > Can you provide a pre training model？ThX.
> 
> Sorry we do not plan to release the pre-trained model for now. You can train one using a GPU with 32GB RAM. The whole training process takes around one day. And in order to get the best result on a certain dataset (e.g., CROHME 2019), you need to set it as the validation dataset.

OK
