### ISSUE TITLE
Can you provide more details about HME100K dataset

### ISSUE THREAD

**Issue by YRQ66** [LBH1024/CAN#21]
Can you provide more details about the config of optimizer used for HME100K dataset?

Thanks!

**Comment by LBH1024** [comment]
按照以下参数进行训练：

epochs: 90
batch_size: 8
workers: 0
train_parts: 3
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta
lr: 1
lr_decay: cosine
eps: 1e-6
weight_decay: 2e-5
beta: 0.9

**Comment by YRQ66** [comment]
thinks
