### ISSUE TITLE
ABM中添加计数模块：（1）L2R和R2L共享计数模块的特征（2）分别在各个分支中添加计数模块？

### ISSUE THREAD

**Issue by kingqiuol** [LBH1024/CAN#23]
我目前的做法是分别在各个分支中添加计数模块，但是还没得到我想要的结果

**Comment by kingqiuol** [comment]
我目前的做法是在各个分支中添加计数模块

**Comment by LBH1024** [comment]
在各个分支中添加计数模块，推荐在该仓库代码基础上进行修改。

**Comment by kingqiuol** [comment]
> 在各个分支中添加计数模块，推荐在该仓库代码基础上进行修改。

谢谢解答，我再研究下
