### ISSUE TITLE
About reproduction performance

### ISSUE THREAD

**Issue by JackyLiu-SCUT** [LBH1024/CAN#5]
Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?

**Comment by LBH1024** [comment]
> Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?

Maybe you can tell me your adjustment(e.g., batch size)?

**Comment by JackyLiu-SCUT** [comment]
> > Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?
> 
> Maybe you can tell me your adjustment(e.g., batch size)?

I change batch size=8 to batch size=2, other parameters stay the same.
I'll try batch size=8 and get back to you. Is batch size so important to the results?

**Comment by LBH1024** [comment]
> > > Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?
> > 
> > 
> > Maybe you can tell me your adjustment(e.g., batch size)?
> 
> I change batch size=8 to batch size=2, other parameters stay the same. I'll try batch size=8 and get back to you. Is batch size so important to the results?

Yes, at least on CROHME it is.

**Comment by LBH1024** [comment]
> > > Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?
> > 
> > 
> > Maybe you can tell me your adjustment(e.g., batch size)?
> 
> I change batch size=8 to batch size=2, other parameters stay the same. I'll try batch size=8 and get back to you. Is batch size so important to the results?

Hi, does changing the batch size to 8 solve your problem?

**Comment by JackyLiu-SCUT** [comment]
> > > > Greetings, I have reproduced according to your code and parameter with almost no adjustment. And my results on three CROHME test set is 10% lower than your paper results. Would you share your experiment log?
> > > 
> > > 
> > > Maybe you can tell me your adjustment(e.g., batch size)?
> > 
> > 
> > I change batch size=8 to batch size=2, other parameters stay the same. I'll try batch size=8 and get back to you. Is batch size so important to the results?
> 
> Hi, does changing the batch size to 8 solve your problem?

Sorry I have been too busy to reply last week. As it turns out, changing batch size to 8 does improve performance by 9% compared to batch size=2. Now my replication is only 1% lower than your paper result, I think I can close the issue now. Thanks again for your contribution and your reply. Wish you happiness every day!

**Comment by SuperHHzy** [comment]
Hi, have you encountered any such problems during the replication of the experiment? I am replicating exactly according to the author's code and parameters, but this problem occurs when I run it. I checked the path to words_dict.txt and the related code as suggested by the author and found no problem.
![image](https://user-images.githubusercontent.com/107484371/188531678-0731d008-c824-4db3-9380-9ad09d198696.png)

**Comment by JackyLiu-SCUT** [comment]
I am sorry. I have encountered no such problems. Maybe you should check the variable labels during debugging? It seems that sth wrong with words_dict or labels. You should open a new issue.




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年9月6日(星期二) 上午10:05
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [LBH1024/CAN] About reproduction performance (Issue #5)





 
Hi, have you encountered any such problems during the replication of the experiment? I am replicating exactly according to the author's code and parameters, but this problem occurs when I run it. I checked the path to words_dict.txt and the related code as suggested by the author and found no problem.
